project:
  random_seed: 42
  target: "Category"
  datetime_col: "Dates"
  split:
    type: "temporal"
    cutoff: "2015-04-01"   # placeholder: lo ajustamos con EDA

features:
  categorical:
    - "DayOfWeek"
    - "PdDistrict"
  numeric:
    - "X"
    - "Y"
  text:
    - "Address"

models:
  baseline_logreg:
    enabled: true
    params:
      max_iter: 200
      n_jobs: -1
      solver: "saga"
      multi_class: "multinomial"

  random_forest:
    enabled: true
    params:
      n_estimators: 300
      max_depth: null
      n_jobs: -1
      random_state: 42

  hist_gb:
    enabled: true
    params:
      max_depth: null
      learning_rate: 0.1
      random_state: 42

mlflow:
  tracking_uri: "file:./mlruns"
  experiment_name: "sf-crime-classification"
